<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	// $data = [
    	// 	['nationality' => 'Afghan', 'sort_order' => 1],
    	// 	['nationality' => 'Albanian', 'sort_order' => 1],
    	// 	['nationality' => 'Algerian', 'sort_order' => 1],
    	// 	['nationality' => 'American', 'sort_order' => 100],
    	// 	['nationality' => 'Andorran', 'sort_order' => 1],
    	// 	['nationality' => 'Angolan', 'sort_order' => 1],
    	// 	['nationality' => 'Anguillan', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of Antigua and Barbuda', 'sort_order' => 1],
    	// 	['nationality' => 'Argentine', 'sort_order' => 1],
    	// 	['nationality' => 'Armenian', 'sort_order' => 1],
    	// 	['nationality' => 'Australian', 'sort_order' => 1],
    	// 	['nationality' => 'Austrian', 'sort_order' => 1],
    	// 	['nationality' => 'Azerbaijani', 'sort_order' => 1],
    	// 	['nationality' => 'Bahamian', 'sort_order' => 1],
    	// 	['nationality' => 'Bahraini', 'sort_order' => 1],
    	// 	['nationality' => 'Bangladeshi', 'sort_order' => 1],
    	// 	['nationality' => 'Barbadian', 'sort_order' => 1],
    	// 	['nationality' => 'Belarusian', 'sort_order' => 1],
    	// 	['nationality' => 'Belgian', 'sort_order' => 100],
    	// 	['nationality' => 'Belizean', 'sort_order' => 1],
    	// 	['nationality' => 'Beninese', 'sort_order' => 1],
    	// 	['nationality' => 'Bermudian', 'sort_order' => 1],
    	// 	['nationality' => 'Bhutanese', 'sort_order' => 1],
    	// 	['nationality' => 'Bolivian', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of Bosnia and Herzegovina', 'sort_order' => 1],
    	// 	['nationality' => 'Botswanan', 'sort_order' => 1],
    	// 	['nationality' => 'Brazilian', 'sort_order' => 1],
    	// 	['nationality' => 'British', 'sort_order' => 100],
    	// 	['nationality' => 'British Virgin Islander', 'sort_order' => 1],
    	// 	['nationality' => 'Bruneian', 'sort_order' => 1],
    	// 	['nationality' => 'Bulgarian', 'sort_order' => 1],
    	// 	['nationality' => 'Burkinan', 'sort_order' => 1],
    	// 	['nationality' => 'Burmese', 'sort_order' => 1],
    	// 	['nationality' => 'Burundian', 'sort_order' => 1],
    	// 	['nationality' => 'Cambodian', 'sort_order' => 1],
    	// 	['nationality' => 'Cameroonian', 'sort_order' => 1],
    	// 	['nationality' => 'Canadian', 'sort_order' => 1],
    	// 	['nationality' => 'Cape Verdean', 'sort_order' => 1],
    	// 	['nationality' => 'Cayman Islander', 'sort_order' => 1],
    	// 	['nationality' => 'Central African', 'sort_order' => 1],
    	// 	['nationality' => 'Chadian', 'sort_order' => 1],
    	// 	['nationality' => 'Chilean', 'sort_order' => 1],
    	// 	['nationality' => 'Chinese', 'sort_order' => 100],
    	// 	['nationality' => 'Colombian', 'sort_order' => 1],
    	// 	['nationality' => 'Comoran', 'sort_order' => 1],
    	// 	['nationality' => 'Congolese (Congo)', 'sort_order' => 1],
    	// 	['nationality' => 'Congolese (DRC)', 'sort_order' => 1],
    	// 	['nationality' => 'Cook Islander', 'sort_order' => 1],
    	// 	['nationality' => 'Costa Rican', 'sort_order' => 1],
    	// 	['nationality' => 'Croatian', 'sort_order' => 1],
    	// 	['nationality' => 'Cuban', 'sort_order' => 1],
    	// 	['nationality' => 'Cymraes', 'sort_order' => 1],
    	// 	['nationality' => 'Cymro', 'sort_order' => 1],
    	// 	['nationality' => 'Cypriot', 'sort_order' => 1],
    	// 	['nationality' => 'Czech', 'sort_order' => 1],
    	// 	['nationality' => 'Danish', 'sort_order' => 1],
    	// 	['nationality' => 'Djiboutian', 'sort_order' => 1],
    	// 	['nationality' => 'Dominican', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of the Dominican Republic', 'sort_order' => 1],
    	// 	['nationality' => 'Dutch', 'sort_order' => 100],
    	// 	['nationality' => 'East Timorese', 'sort_order' => 1],
    	// 	['nationality' => 'Ecuadorean', 'sort_order' => 1],
    	// 	['nationality' => 'Egyptian', 'sort_order' => 1],
    	// 	['nationality' => 'Emirati', 'sort_order' => 1],
    	// 	['nationality' => 'English', 'sort_order' => 100],
    	// 	['nationality' => 'Equatorial Guinean', 'sort_order' => 1],
    	// 	['nationality' => 'Eritrean', 'sort_order' => 1],
    	// 	['nationality' => 'Estonian', 'sort_order' => 1],
    	// 	['nationality' => 'Ethiopian', 'sort_order' => 1],
    	// 	['nationality' => 'Faroese', 'sort_order' => 1],
    	// 	['nationality' => 'Fijian', 'sort_order' => 1],
    	// 	['nationality' => 'Filipino', 'sort_order' => 100],
    	// 	['nationality' => 'Finnish', 'sort_order' => 1],
    	// 	['nationality' => 'French', 'sort_order' => 100],
    	// 	['nationality' => 'Gabonese', 'sort_order' => 1],
    	// 	['nationality' => 'Gambian', 'sort_order' => 1],
    	// 	['nationality' => 'Georgian', 'sort_order' => 1],
    	// 	['nationality' => 'German', 'sort_order' => 1000],
    	// 	['nationality' => 'Ghanaian', 'sort_order' => 1],
    	// 	['nationality' => 'Gibraltarian', 'sort_order' => 1],
    	// 	['nationality' => 'Greek', 'sort_order' => 1],
    	// 	['nationality' => 'Greenlandic', 'sort_order' => 1],
    	// 	['nationality' => 'Grenadian', 'sort_order' => 1],
    	// 	['nationality' => 'Guamanian', 'sort_order' => 1],
    	// 	['nationality' => 'Guatemalan', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of Guinea-Bissau', 'sort_order' => 1],
    	// 	['nationality' => 'Guinean', 'sort_order' => 1],
    	// 	['nationality' => 'Guyanese', 'sort_order' => 1],
    	// 	['nationality' => 'Haitian', 'sort_order' => 1],
    	// 	['nationality' => 'Honduran', 'sort_order' => 1],
    	// 	['nationality' => 'Hong Konger', 'sort_order' => 1],
    	// 	['nationality' => 'Hungarian', 'sort_order' => 1],
    	// 	['nationality' => 'Icelandic', 'sort_order' => 1],
    	// 	['nationality' => 'Indian', 'sort_order' => 1],
    	// 	['nationality' => 'Indonesian', 'sort_order' => 1],
    	// 	['nationality' => 'Iranian', 'sort_order' => 1],
    	// 	['nationality' => 'Iraqi', 'sort_order' => 1],
    	// 	['nationality' => 'Irish', 'sort_order' => 1],
    	// 	['nationality' => 'Israeli', 'sort_order' => 1],
    	// 	['nationality' => 'Italian', 'sort_order' => 1],
    	// 	['nationality' => 'Ivorian', 'sort_order' => 1],
    	// 	['nationality' => 'Jamaican', 'sort_order' => 1],
    	// 	['nationality' => 'Japanese', 'sort_order' => 1],
    	// 	['nationality' => 'Jordanian', 'sort_order' => 1],
    	// 	['nationality' => 'Kazakh', 'sort_order' => 1],
    	// 	['nationality' => 'Kenyan', 'sort_order' => 1],
    	// 	['nationality' => 'Kittitian', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of Kiribati', 'sort_order' => 1],
    	// 	['nationality' => 'Kosovan', 'sort_order' => 1],
    	// 	['nationality' => 'Kuwaiti', 'sort_order' => 1],
    	// 	['nationality' => 'Kyrgyz', 'sort_order' => 1],
    	// 	['nationality' => 'Lao', 'sort_order' => 1],
    	// 	['nationality' => 'Latvian', 'sort_order' => 1],
    	// 	['nationality' => 'Lebanese', 'sort_order' => 1],
    	// 	['nationality' => 'Liberian', 'sort_order' => 1],
    	// 	['nationality' => 'Libyan', 'sort_order' => 1],
    	// 	['nationality' => 'Liechtenstein citizen', 'sort_order' => 1],
    	// 	['nationality' => 'Lithuanian', 'sort_order' => 1],
    	// 	['nationality' => 'Luxembourger', 'sort_order' => 1],
    	// 	['nationality' => 'Macanese', 'sort_order' => 1],
    	// 	['nationality' => 'Macedonian', 'sort_order' => 1],
    	// 	['nationality' => 'Malagasy', 'sort_order' => 1],
    	// 	['nationality' => 'Malawian', 'sort_order' => 1],
    	// 	['nationality' => 'Malaysian', 'sort_order' => 1],
    	// 	['nationality' => 'Maldivian', 'sort_order' => 1],
    	// 	['nationality' => 'Malian', 'sort_order' => 1],
    	// 	['nationality' => 'Maltese', 'sort_order' => 1],
    	// 	['nationality' => 'Marshallese', 'sort_order' => 1],
    	// 	['nationality' => 'Martiniquais', 'sort_order' => 1],
    	// 	['nationality' => 'Mauritanian', 'sort_order' => 1],
    	// 	['nationality' => 'Mauritian', 'sort_order' => 1],
    	// 	['nationality' => 'Mexican', 'sort_order' => 1],
    	// 	['nationality' => 'Micronesian', 'sort_order' => 1],
    	// 	['nationality' => 'Moldovan', 'sort_order' => 1],
    	// 	['nationality' => 'Monegasque', 'sort_order' => 1],
    	// 	['nationality' => 'Mongolian', 'sort_order' => 1],
    	// 	['nationality' => 'Montenegrin', 'sort_order' => 1],
    	// 	['nationality' => 'Montserratian', 'sort_order' => 1],
    	// 	['nationality' => 'Moroccan', 'sort_order' => 1],
    	// 	['nationality' => 'Mosotho', 'sort_order' => 1],
    	// 	['nationality' => 'Mozambican', 'sort_order' => 1],
    	// 	['nationality' => 'Namibian', 'sort_order' => 1],
    	// 	['nationality' => 'Nauruan', 'sort_order' => 1],
    	// 	['nationality' => 'Nepalese', 'sort_order' => 1],
    	// 	['nationality' => 'New Zealander', 'sort_order' => 1],
    	// 	['nationality' => 'Nicaraguan', 'sort_order' => 1],
    	// 	['nationality' => 'Nigerian', 'sort_order' => 1],
    	// 	['nationality' => 'Nigerien', 'sort_order' => 1],
    	// 	['nationality' => 'Niuean', 'sort_order' => 1],
    	// 	['nationality' => 'North Korean', 'sort_order' => 1],
    	// 	['nationality' => 'Northern Irish', 'sort_order' => 1],
    	// 	['nationality' => 'Norwegian', 'sort_order' => 1],
    	// 	['nationality' => 'Omani', 'sort_order' => 1],
    	// 	['nationality' => 'Pakistani', 'sort_order' => 1],
    	// 	['nationality' => 'Palauan', 'sort_order' => 1],
    	// 	['nationality' => 'Palestinian', 'sort_order' => 1],
    	// 	['nationality' => 'Panamanian', 'sort_order' => 1],
    	// 	['nationality' => 'Papua New Guinean', 'sort_order' => 1],
    	// 	['nationality' => 'Paraguayan', 'sort_order' => 1],
    	// 	['nationality' => 'Peruvian', 'sort_order' => 1],
    	// 	['nationality' => 'Pitcairn Islander', 'sort_order' => 1],
    	// 	['nationality' => 'Polish', 'sort_order' => 1],
    	// 	['nationality' => 'Portuguese', 'sort_order' => 1],
    	// 	['nationality' => 'Prydeinig', 'sort_order' => 1],
    	// 	['nationality' => 'Puerto Rican', 'sort_order' => 1],
    	// 	['nationality' => 'Qatari', 'sort_order' => 1],
    	// 	['nationality' => 'Romanian', 'sort_order' => 1],
    	// 	['nationality' => 'Russian', 'sort_order' => 1],
    	// 	['nationality' => 'Rwandan', 'sort_order' => 1],
    	// 	['nationality' => 'Salvadorean', 'sort_order' => 1],
    	// 	['nationality' => 'Sammarinese', 'sort_order' => 1],
    	// 	['nationality' => 'Samoan', 'sort_order' => 1],
    	// 	['nationality' => 'Sao Tomean', 'sort_order' => 1],
    	// 	['nationality' => 'Saudi Arabian', 'sort_order' => 1],
    	// 	['nationality' => 'Scottish', 'sort_order' => 1],
    	// 	['nationality' => 'Senegalese', 'sort_order' => 1],
    	// 	['nationality' => 'Serbian', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of Seychelles', 'sort_order' => 1],
    	// 	['nationality' => 'Sierra Leonean', 'sort_order' => 1],
    	// 	['nationality' => 'Singaporean', 'sort_order' => 1],
    	// 	['nationality' => 'Slovak', 'sort_order' => 1],
    	// 	['nationality' => 'Slovenian', 'sort_order' => 1],
    	// 	['nationality' => 'Solomon Islander', 'sort_order' => 1],
    	// 	['nationality' => 'Somali', 'sort_order' => 1],
    	// 	['nationality' => 'South African', 'sort_order' => 100],
    	// 	['nationality' => 'South Korean', 'sort_order' => 1],
    	// 	['nationality' => 'South Sudanese', 'sort_order' => 1],
    	// 	['nationality' => 'Spanish', 'sort_order' => 1],
    	// 	['nationality' => 'Sri Lankan', 'sort_order' => 1],
    	// 	['nationality' => 'St Helenian', 'sort_order' => 1],
    	// 	['nationality' => 'St Lucian', 'sort_order' => 1],
    	// 	['nationality' => 'Stateless', 'sort_order' => 1],
    	// 	['nationality' => 'Sudanese', 'sort_order' => 1],
    	// 	['nationality' => 'Surinamese', 'sort_order' => 1],
    	// 	['nationality' => 'Swazi', 'sort_order' => 1],
    	// 	['nationality' => 'Swedish', 'sort_order' => 1],
    	// 	['nationality' => 'Swiss', 'sort_order' => 1],
    	// 	['nationality' => 'Syrian', 'sort_order' => 1],
    	// 	['nationality' => 'Taiwanese', 'sort_order' => 1],
    	// 	['nationality' => 'Tajik', 'sort_order' => 1],
    	// 	['nationality' => 'Tanzanian', 'sort_order' => 1],
    	// 	['nationality' => 'Thai', 'sort_order' => 1],
    	// 	['nationality' => 'Togolese', 'sort_order' => 1],
    	// 	['nationality' => 'Tongan', 'sort_order' => 1],
    	// 	['nationality' => 'Trinidadian', 'sort_order' => 1],
    	// 	['nationality' => 'Tristanian', 'sort_order' => 1],
    	// 	['nationality' => 'Tunisian', 'sort_order' => 1],
    	// 	['nationality' => 'Turkish', 'sort_order' => 1],
    	// 	['nationality' => 'Turkmen', 'sort_order' => 1],
    	// 	['nationality' => 'Turks and Caicos Islander', 'sort_order' => 1],
    	// 	['nationality' => 'Tuvaluan', 'sort_order' => 1],
    	// 	['nationality' => 'Ugandan', 'sort_order' => 1],
    	// 	['nationality' => 'Ukrainian', 'sort_order' => 1],
    	// 	['nationality' => 'Uruguayan', 'sort_order' => 1],
    	// 	['nationality' => 'Uzbek', 'sort_order' => 1],
    	// 	['nationality' => 'Vatican citizen', 'sort_order' => 1],
    	// 	['nationality' => 'Citizen of Vanuatu', 'sort_order' => 1],
    	// 	['nationality' => 'Venezuelan', 'sort_order' => 1],
    	// 	['nationality' => 'Vietnamese', 'sort_order' => 1000],
    	// 	['nationality' => 'Vincentian', 'sort_order' => 1],
    	// 	['nationality' => 'Wallisian', 'sort_order' => 1],
    	// 	['nationality' => 'Welsh', 'sort_order' => 1],
    	// 	['nationality' => 'Yemeni', 'sort_order' => 1],
    	// 	['nationality' => 'Zambian', 'sort_order' => 1],
    	// 	['nationality' => 'Zimbabwean', 'sort_order' => 1],
    	// ];
    	$data = [
    		['country' => 'Afghanistan', 'sort_order' => 1],
    		['country' => 'Aland Islands', 'sort_order' => 1],
    		['country' => 'Albania', 'sort_order' => 1],
    		['country' => 'Algeria', 'sort_order' => 1],
    		['country' => 'American Samoa', 'sort_order' => 1],
    		['country' => 'Andorra', 'sort_order' => 1],
    		['country' => 'Angola', 'sort_order' => 1],
    		['country' => 'Anguilla', 'sort_order' => 1],
    		['country' => 'Antarctica', 'sort_order' => 1],
    		['country' => 'Antigua and Barbuda', 'sort_order' => 1],
    		['country' => 'Argentina', 'sort_order' => 1],
    		['country' => 'Armenia', 'sort_order' => 1],
    		['country' => 'Aruba', 'sort_order' => 1],
    		['country' => 'Australia', 'sort_order' => 1],
    		['country' => 'Austria', 'sort_order' => 1],
    		['country' => 'Azerbaijan', 'sort_order' => 1],
    		['country' => 'Bahamas', 'sort_order' => 1],
    		['country' => 'Bahrain', 'sort_order' => 1],
    		['country' => 'Bangladesh', 'sort_order' => 1],
    		['country' => 'Barbados', 'sort_order' => 1],
    		['country' => 'Belarus', 'sort_order' => 1],
    		['country' => 'Belgium', 'sort_order' => 100],
    		['country' => 'Belize', 'sort_order' => 1],
    		['country' => 'Benin', 'sort_order' => 1],
    		['country' => 'Bermuda', 'sort_order' => 1],
    		['country' => 'Bhutan', 'sort_order' => 1],
    		['country' => 'Bolivia', 'sort_order' => 1],
    		['country' => 'Bonaire, Sint Eustatius and Saba', 'sort_order' => 1],
    		['country' => 'Bosnia and Herzegovina', 'sort_order' => 1],
    		['country' => 'Botswana', 'sort_order' => 1],
    		['country' => 'Bouvet Island', 'sort_order' => 1],
    		['country' => 'Brazil', 'sort_order' => 1],
    		['country' => 'British Indian Ocean Territory', 'sort_order' => 1],
    		['country' => 'Brunei Darussalam', 'sort_order' => 1],
    		['country' => 'Bulgaria', 'sort_order' => 1],
    		['country' => 'Burkina Faso', 'sort_order' => 1],
    		['country' => 'Burma', 'sort_order' => 1],
    		['country' => 'Burundi', 'sort_order' => 1],
    		['country' => 'Cambodia', 'sort_order' => 1],
    		['country' => 'Cameroon', 'sort_order' => 1],
    		['country' => 'Canada', 'sort_order' => 1],
    		['country' => 'Cape Verde', 'sort_order' => 1],
    		['country' => 'Cayman Islands', 'sort_order' => 1],
    		['country' => 'Central African Republic', 'sort_order' => 1],
    		['country' => 'Chad', 'sort_order' => 1],
    		['country' => 'Chile', 'sort_order' => 1],
    		['country' => 'China', 'sort_order' => 100],
    		['country' => 'Christmas Island', 'sort_order' => 1],
    		['country' => 'Cocos (Keeling) Islands', 'sort_order' => 1],
    		['country' => 'Colombia', 'sort_order' => 1],
    		['country' => 'Comoros', 'sort_order' => 1],
    		['country' => 'Congo', 'sort_order' => 1],
    		['country' => 'Congo, the Democratic Republic of the', 'sort_order' => 1],
    		['country' => 'Cook Islands', 'sort_order' => 1],
    		['country' => 'Costa Rica', 'sort_order' => 1],
    		['country' => 'Croatia', 'sort_order' => 1],
    		['country' => 'Cuba', 'sort_order' => 1],
    		['country' => 'Curacao', 'sort_order' => 1],
    		['country' => 'Cyprus', 'sort_order' => 1],
    		['country' => 'Czech Republic', 'sort_order' => 1],
    		['country' => 'Denmark', 'sort_order' => 1],
    		['country' => 'Djibouti', 'sort_order' => 1],
    		['country' => 'Dominica', 'sort_order' => 1],
    		['country' => 'Dominican Republic', 'sort_order' => 1],
    		['country' => 'East Timor', 'sort_order' => 1],
    		['country' => 'Ecuador', 'sort_order' => 1],
    		['country' => 'Egypt', 'sort_order' => 1],
    		['country' => 'El Salvador', 'sort_order' => 1],
    		['country' => 'England', 'sort_order' => 1],
    		['country' => 'Equatorial Guinea', 'sort_order' => 1],
    		['country' => 'Eritrea', 'sort_order' => 1],
    		['country' => 'Estonia', 'sort_order' => 1],
    		['country' => 'Ethiopia', 'sort_order' => 1],
    		['country' => 'Falkland Islands', 'sort_order' => 1],
    		['country' => 'Faroe Islands', 'sort_order' => 1],
    		['country' => 'Fiji', 'sort_order' => 1],
    		['country' => 'Finland', 'sort_order' => 1],
    		['country' => 'France', 'sort_order' => 100],
    		['country' => 'French Guiana', 'sort_order' => 1],
    		['country' => 'French Polynesia', 'sort_order' => 1],
    		['country' => 'French Southern Territories', 'sort_order' => 1],
    		['country' => 'Gabon', 'sort_order' => 1],
    		['country' => 'Gambia', 'sort_order' => 1],
    		['country' => 'Georgia', 'sort_order' => 1],
    		['country' => 'Germany', 'sort_order' => 1000],
    		['country' => 'Ghana', 'sort_order' => 1],
    		['country' => 'Gibraltar', 'sort_order' => 1],
    		['country' => 'Greece', 'sort_order' => 1],
    		['country' => 'Greenland', 'sort_order' => 1],
    		['country' => 'Grenada', 'sort_order' => 1],
    		['country' => 'Guadeloupe', 'sort_order' => 1],
    		['country' => 'Guam', 'sort_order' => 1],
    		['country' => 'Guatemala', 'sort_order' => 1],
    		['country' => 'Guernsey', 'sort_order' => 1],
    		['country' => 'Guinea', 'sort_order' => 1],
    		['country' => 'Guinea-Bissau', 'sort_order' => 1],
    		['country' => 'Guyana', 'sort_order' => 1],
    		['country' => 'Haiti', 'sort_order' => 1],
    		['country' => 'Heard Island and McDonald Islands', 'sort_order' => 1],
    		['country' => 'Holy See', 'sort_order' => 1],
    		['country' => 'Honduras', 'sort_order' => 1],
    		['country' => 'Hong Kong', 'sort_order' => 1],
    		['country' => 'Hungary', 'sort_order' => 1],
    		['country' => 'Iceland', 'sort_order' => 1],
    		['country' => 'India', 'sort_order' => 1],
    		['country' => 'Indonesia', 'sort_order' => 1],
    		['country' => 'Iran', 'sort_order' => 1],
    		['country' => 'Iraq', 'sort_order' => 1],
    		['country' => 'Ireland', 'sort_order' => 1],
    		['country' => 'Isle of Man', 'sort_order' => 1],
    		['country' => 'Israel', 'sort_order' => 1],
    		['country' => 'Italy', 'sort_order' => 1],
    		['country' => 'Ivory Coast', 'sort_order' => 1],
    		['country' => 'Jamaica', 'sort_order' => 1],
    		['country' => 'Japan', 'sort_order' => 1],
    		['country' => 'Jersey', 'sort_order' => 1],
    		['country' => 'Jordan', 'sort_order' => 1],
    		['country' => 'Kazakhstan', 'sort_order' => 1],
    		['country' => 'Kenya', 'sort_order' => 1],
    		['country' => 'Kiribati', 'sort_order' => 1],
    		['country' => 'Kosovo', 'sort_order' => 1],
    		['country' => 'Kuwait', 'sort_order' => 1],
    		['country' => 'Kyrgyzstan', 'sort_order' => 1],
    		['country' => 'Laos', 'sort_order' => 1],
    		['country' => 'Latvia', 'sort_order' => 1],
    		['country' => 'Lebanon', 'sort_order' => 1],
    		['country' => 'Lesotho', 'sort_order' => 1],
    		['country' => 'Liberia', 'sort_order' => 1],
    		['country' => 'Libya', 'sort_order' => 1],
    		['country' => 'Liechtenstein', 'sort_order' => 1],
    		['country' => 'Lithuania', 'sort_order' => 1],
    		['country' => 'Luxembourg', 'sort_order' => 1],
    		['country' => 'Macao', 'sort_order' => 1],
    		['country' => 'Macedonia', 'sort_order' => 1],
    		['country' => 'Madagascar', 'sort_order' => 1],
    		['country' => 'Malawi', 'sort_order' => 1],
    		['country' => 'Malaysia', 'sort_order' => 1],
    		['country' => 'Maldives', 'sort_order' => 1],
    		['country' => 'Mali', 'sort_order' => 1],
    		['country' => 'Malta', 'sort_order' => 1],
    		['country' => 'Marshall Islands', 'sort_order' => 1],
    		['country' => 'Martinique', 'sort_order' => 1],
    		['country' => 'Mauritania', 'sort_order' => 1],
    		['country' => 'Mauritius', 'sort_order' => 1],
    		['country' => 'Mayotte', 'sort_order' => 1],
    		['country' => 'Mexico', 'sort_order' => 1],
    		['country' => 'Micronesia', 'sort_order' => 1],
    		['country' => 'Moldova', 'sort_order' => 1],
    		['country' => 'Monaco', 'sort_order' => 1],
    		['country' => 'Mongolia', 'sort_order' => 1],
    		['country' => 'Montenegro', 'sort_order' => 1],
    		['country' => 'Montserrat', 'sort_order' => 1],
    		['country' => 'Morocco', 'sort_order' => 1],
    		['country' => 'Mozambique', 'sort_order' => 1],
    		['country' => 'Myanmar', 'sort_order' => 1],
    		['country' => 'Namibia', 'sort_order' => 1],
    		['country' => 'Nauru', 'sort_order' => 1],
    		['country' => 'Nepal', 'sort_order' => 1],
    		['country' => 'Netherlands', 'sort_order' => 100],
    		['country' => 'New Caledonia', 'sort_order' => 1],
    		['country' => 'New Zealand', 'sort_order' => 1],
    		['country' => 'Nicaragua', 'sort_order' => 1],
    		['country' => 'Niger', 'sort_order' => 1],
    		['country' => 'Nigeria', 'sort_order' => 1],
    		['country' => 'Niue', 'sort_order' => 1],
    		['country' => 'Norfolk Island', 'sort_order' => 1],
    		['country' => 'North Korea', 'sort_order' => 1],
    		['country' => 'Northern Ireland', 'sort_order' => 1],
    		['country' => 'Northern Mariana Islands', 'sort_order' => 1],
    		['country' => 'Norway', 'sort_order' => 1],
    		['country' => 'Oman', 'sort_order' => 1],
    		['country' => 'Pakistan', 'sort_order' => 1],
    		['country' => 'Palau', 'sort_order' => 1],
    		['country' => 'Palestine, State of', 'sort_order' => 1],
    		['country' => 'Panama', 'sort_order' => 1],
    		['country' => 'Papua New Guinea', 'sort_order' => 1],
    		['country' => 'Paraguay', 'sort_order' => 1],
    		['country' => 'Peru', 'sort_order' => 1],
    		['country' => 'Philippines', 'sort_order' => 100],
    		['country' => 'Pitcairn', 'sort_order' => 1],
    		['country' => 'Poland', 'sort_order' => 1],
    		['country' => 'Portugal', 'sort_order' => 1],
    		['country' => 'Puerto Rico', 'sort_order' => 1],
    		['country' => 'Qatar', 'sort_order' => 1],
    		['country' => 'Reunion', 'sort_order' => 1],
    		['country' => 'Romania', 'sort_order' => 1],
    		['country' => 'Russia', 'sort_order' => 1],
    		['country' => 'Rwanda', 'sort_order' => 1],
    		['country' => 'Saint Barthelemy', 'sort_order' => 1],
    		['country' => 'Saint Helena, Ascension and Tristan da Cunha', 'sort_order' => 1],
    		['country' => 'Saint Kitts and Nevis', 'sort_order' => 1],
    		['country' => 'Saint Lucia', 'sort_order' => 1],
    		['country' => 'Saint Martin (French part)', 'sort_order' => 1],
    		['country' => 'Saint Pierre and Miquelon', 'sort_order' => 1],
    		['country' => 'Saint Vincent', 'sort_order' => 1],
    		['country' => 'Saint Vincent and the Grenadines', 'sort_order' => 1],
    		['country' => 'Samoa', 'sort_order' => 1],
    		['country' => 'San Marino', 'sort_order' => 1],
    		['country' => 'Sao Tome and Principe', 'sort_order' => 1],
    		['country' => 'Saudi Arabia', 'sort_order' => 1],
    		['country' => 'Scotland', 'sort_order' => 1],
    		['country' => 'Senegal', 'sort_order' => 1],
    		['country' => 'Serbia', 'sort_order' => 1],
    		['country' => 'Seychelles', 'sort_order' => 1],
    		['country' => 'Sierra Leone', 'sort_order' => 1],
    		['country' => 'Singapore', 'sort_order' => 1],
    		['country' => 'Sint Maarten (Dutch part)', 'sort_order' => 1],
    		['country' => 'Slovakia', 'sort_order' => 1],
    		['country' => 'Slovenia', 'sort_order' => 1],
    		['country' => 'Solomon Islands', 'sort_order' => 1],
    		['country' => 'Somalia', 'sort_order' => 1],
    		['country' => 'South Africa', 'sort_order' => 100],
    		['country' => 'South Georgia and the South Sandwich Islands', 'sort_order' => 1],
    		['country' => 'South Korea', 'sort_order' => 1],
    		['country' => 'South Sudan', 'sort_order' => 1],
    		['country' => 'Spain', 'sort_order' => 1],
    		['country' => 'Sri Lanka', 'sort_order' => 1],
    		['country' => 'Sudan', 'sort_order' => 1],
    		['country' => 'Suriname', 'sort_order' => 1],
    		['country' => 'Svalbard and Jan Mayen', 'sort_order' => 1],
    		['country' => 'Swaziland', 'sort_order' => 1],
    		['country' => 'Sweden', 'sort_order' => 1],
    		['country' => 'Switzerland', 'sort_order' => 1],
    		['country' => 'Syria', 'sort_order' => 1],
    		['country' => 'Taiwan', 'sort_order' => 1],
    		['country' => 'Tajikistan', 'sort_order' => 1],
    		['country' => 'Tanzania', 'sort_order' => 1],
    		['country' => 'Thailand', 'sort_order' => 1],
    		['country' => 'Timor-Leste', 'sort_order' => 1],
    		['country' => 'Togo', 'sort_order' => 1],
    		['country' => 'Tokelau', 'sort_order' => 1],
    		['country' => 'Tonga', 'sort_order' => 1],
    		['country' => 'Trinidad and Tobago', 'sort_order' => 1],
    		['country' => 'Tunisia', 'sort_order' => 1],
    		['country' => 'Turkey', 'sort_order' => 1],
    		['country' => 'Turkmenistan', 'sort_order' => 1],
    		['country' => 'Turks and Caicos Islands', 'sort_order' => 1],
    		['country' => 'Tuvalu', 'sort_order' => 1],
    		['country' => 'Uganda', 'sort_order' => 1],
    		['country' => 'Ukraine', 'sort_order' => 1],
    		['country' => 'United Arab Emirates', 'sort_order' => 1],
    		['country' => 'United Kingdom', 'sort_order' => 100],
    		['country' => 'United States', 'sort_order' => 100],
    		['country' => 'United States Minor Outlying Islands', 'sort_order' => 1],
    		['country' => 'Uruguay', 'sort_order' => 1],
    		['country' => 'Uzbekistan', 'sort_order' => 1],
    		['country' => 'Vanuatu', 'sort_order' => 1],
    		['country' => 'Vatican City', 'sort_order' => 1],
    		['country' => 'Venezuela', 'sort_order' => 1],
    		['country' => 'Vietnam', 'sort_order' => 1000],
    		['country' => 'Virgin Islands, British', 'sort_order' => 1],
    		['country' => 'Virgin Islands, U.S.', 'sort_order' => 1],
    		['country' => 'Wales', 'sort_order' => 1],
    		['country' => 'Wallis and Futuna', 'sort_order' => 1],
    		['country' => 'Western Sahara', 'sort_order' => 1],
    		['country' => 'Yemen', 'sort_order' => 1],
    		['country' => 'Zambia', 'sort_order' => 1],
    		['country' => 'Zimbabwe', 'sort_order' => 1],
    	];

    	DB::table('nationalities')->delete();
    	DB::table('nationalities')->insert($data);
    }
}
